embeddings {
  tensor_name: "token_embedding/token_embedding_weights:0"
  metadata_path: "outputvietnam\\du_doan_2020-05-31_15-54-18-379949\\model\\tensorboard_metadata_tokens.tsv"
}
embeddings {
  tensor_name: "character_embedding/character_embedding_weights:0"
  metadata_path: "outputvietnam\\du_doan_2020-05-31_15-54-18-379949\\model\\tensorboard_metadata_characters.tsv"
}
